### ISSUE TITLE
Link to migration guide is broken

### ISSUE THREAD

**Issue by ArekPiekarz** [Relm4/website#6]
The page with a blog post about Relm4 0.5 - https://relm4.org/blog/posts/announcing_relm4_v0.5/ - contains a link to "Migration guide" - https://relm4.org/book/stable/0_4_to_0_5.html - but it leads to an error:

> 404
> File not found
> 
> The site configured at this address does not contain the requested file.
> 
> If this is your site, make sure that the filename case matches the URL.
> For root URLs (like http://example.com/) you must provide an index.html file.
> 
> [Read the full documentation](https://help.github.com/pages/) for more information about using GitHub Pages.

**Comment by AaronErhardt** [comment]
Thanks! We forgot to switch branches so that 0.5 is the new stable. I've updates this now, which should also fix the other issue at the same time: https://github.com/Relm4/book/issues/39
